# Generated by Django 5.2.1 on 2025-06-16 09:55

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_unique_name_mynotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='unique_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='unique_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
