# Generated by Django 5.2.1 on 2025-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_blocked_until_user_last_unblocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
