# Generated by Django 5.2.1 on 2025-05-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_slot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglog',
            name='deleted_slot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='slot_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.slot'),
        ),
    ]
