# Generated by Django 5.2.1 on 2025-05-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_bookinglog_deleted_slot_id_bookinglog_slot_str_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglog',
            name='deleted_slot_id',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='slot_str',
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
