# Generated by Django 5.2.1 on 2025-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_slot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=60, max_length=3, null=True),
        ),
    ]
