# Generated by Django 5.2.1 on 2025-06-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_slot_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
