# Generated by Django 5.2.1 on 2025-05-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_created_at'),
        ('schedule', '0002_slot_user_alter_slot_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_slot', to='schedule.slot'),
        ),
    ]
